### ISSUE TITLE
严重BUG

### ISSUE THREAD

**Issue by internetWei** [SilverFruity/UICornerShadowView#2]
前提：APP适配了暗黑主题
当前在一个UITableView页面，当APP退到后台重新进入时，某些Cell会出现白色背景。经过排查发现是SFCBView内部的UIImageView对象变成了白色导致的。详情可以参考[图1链接](https://pic.downk.cc/item/5fbc3c22b18d627113188064.png)、[图2链接](https://pic.downk.cc/item/5fbc3c46b18d627113188400.png)、[图3链接](https://pic.downk.cc/item/5fbc3c58b18d6271131885e2.png)。如果链接打不开可以联系我(internetwei@foxmail.com)

**Comment by SilverFruity** [comment]
请问系统版本是多少呢？我使用Demo在iOS 13.3下进行测试，是无法复现这个问题的。希望能够给我提供一个完整的复现途径。

**Comment by internetWei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    CocoaPods最新版本：1.0.2
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                internetwei
                            
                    
                        
                            
                                    internetwei@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年11月24日 15:06，Ke Ming Jiang<notifications@github.com> 写道： 




请问系统版本是多少呢？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SilverFruity** [comment]
😂😂

**Comment by SilverFruity** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } CocoaPods最新版本：1.0.2 internetwei internetwei@foxmail.com 签名由 网易邮箱大师 定制 在2020年11月24日 15:06，Ke Ming Jiang<notifications@github.com> 写道： 请问系统版本是多少呢？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

你发的，我根本看不见啊😭

**Comment by internetWei** [comment]
没事了，问题已经解决了。

**Comment by SilverFruity** [comment]
> 没事了，问题已经解决了。

是设置代码的问题吗？还是库的问题呢？

**Comment by internetWei** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    暂时还不清楚是库的问题还是代码设置的问题，我明天再看看确认一下问题在哪，然后在联系您。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                internetwei
                            
                    
                        
                            
                                    internetwei@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年01月19日 23:56，Ke Ming Jiang<notifications@github.com> 写道： 






没事了，问题已经解决了。



是设置代码的问题吗？还是库的问题呢？



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SilverFruity** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 暂时还不清楚是库的问题还是代码设置的问题，我明天再看看确认一下问题在哪，然后在联系您。 internetwei internetwei@foxmail.com 签名由 网易邮箱大师 定制 在2021年01月19日 23:56，Ke Ming Jiang<notifications@github.com> 写道： 没事了，问题已经解决了。 是设置代码的问题吗？还是库的问题呢？ —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

好的哦，谢谢🙏，晚安😴

**Comment by internetWei** [comment]
您好。
问题已经找到了，原因是因为`SFCSBView`内部有一个`backGroundImageView`的UIIMageView属性。它的image决定了View的背景。当切换深色模式时只是刷新了UIColor属性，image属性没有更新导致背景颜色没有刷新。详情可以查看底下我上传的3张图片。
[图片1链接](https://p.pstatp.com/origin/137b200018af68b67b6c6) [图片2链接](https://p.pstatp.com/origin/1374900026e2c82da1409) [图片3链接](https://p.pstatp.com/origin/138130001b727aa71af78)

**Comment by SilverFruity** [comment]
这个问题的解决已经提交到1.0.3了。
原因：在系统切换夜间模式的时候，UIDynamicSystemColor的RGB会被改变，但是它的hash值不会改变（SFCSBView内部使用的是hash值来表示UIColor颜色的唯一性），这个时候使用图片的identfier从缓存中获取到的依然是之前的白色图片。
解决办法：将UIColor的identifer使用RGB值来表示，即可解决这个问题。
感谢你的issue。
