### ISSUE TITLE
怎么给类似imageView设置阴影圆角效果

### ISSUE THREAD

**Issue by FoneG** [SilverFruity/UICornerShadowView#3]

**Comment by SilverFruity** [comment]
抱歉，没看懂具体的需求

**Comment by FoneG** [comment]
> 抱歉，没看懂具体的需求

抱歉前面没整理好提问思路，这边提个新问题

场景如下：
有一个SFCSBView，白色背景  上面添加一个subView：UIImageView，该UIImageView的，edges跟父视图对齐

我看SFCSBView内部贴backGroundImageView实现的，而backGroundImageView的frame一般是超出SFCSBView的。最后导致了 UIImageView和SFCSBView之间有个白色空隙。

**Comment by SilverFruity** [comment]
> > 抱歉，没看懂具体的需求
> 
> 抱歉前面没整理好提问思路，这边提个新问题
> 
> 场景如下： 有一个SFCSBView，白色背景 上面添加一个subView：UIImageView，该UIImageView的，edges跟父视图对齐
> 
> 我看SFCSBView内部贴backGroundImageView实现的，而backGroundImageView的frame一般是超出SFCSBView的。最后导致了 UIImageView和SFCSBView之间有个白色空隙。

`insertValue` 之前为了解决列表页阴影视觉上有空缺加入的，结果导致了目前这个问题

**Comment by SilverFruity** [comment]
1.1.3 上已经解决，记得 pod repo update
