### ISSUE TITLE
darkMode 问题

### ISSUE THREAD

**Issue by snaillovesmile** [SilverFruity/UICornerShadowView#4]
当app在后台运行, 这时候切换darkmode 再讲app 进入前台, 这时候的view 背景颜色会出问题(不发生改变)

**Comment by SilverFruity** [comment]
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/16136774/178013523-e2fb8f07-bfad-496f-9496-78bf46ddc3af.png">
App 启动后，直接退到后台时，layoutSubviews 会被连续调用两次，并且两次的 color 值是不同的，同时由于是异步调用，在 ColorImageGenerator 生成图片时，原本 self.color 为白色，但此时却被系统修改为黑色，导致原本属于白色图片的 identifier 被设置成了一张黑色图片，最终导致了这个问题。

**Comment by SilverFruity** [comment]
1.1.4 已经解决
